In [310]:
import json
import os
from io import StringIO
from pathlib import Path

import pandas as pd
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from loguru import logger

from unga81.database import get_all_countries, get_db_connection
from unga81.config import EXTERNAL_DATA_DIR, PROCESSED_DATA_DIR
from unga81.restcountries import download_country_data

pd.options.display.max_columns = None
pd.options.display.max_rows = None
# pd.options.display.max_rows = 20

load_dotenv()

API_KEY = os.getenv("API_KEY_RESTCOUNTRIES")

In [311]:
conn = get_db_connection()
df = get_all_countries(conn=conn)
logger.info(f"{df.shape[0]} speeches in the database")

2026-09-28 04:08:56.808 | INFO     | __main__:<module>:3 - 176 speeches in the database

# RestcountriesAPI

In [ ]:
country_information_path = EXTERNAL_DATA_DIR / "restcountriesapi"
country_information_path.mkdir(parents=True, exist_ok=True)


for i, r in df.iterrows():
    if isinstance(r["iso_3"], str):
        download_country_data(alpha_3=r["iso_3"], output_path=country_information_path)

In [ ]:
# name_common = data_pais["data"]["objects"][0]["names"]["common"]
# name_official = data_pais["data"]["objects"][0]["names"]["official"]
# lat, lng = data_pais["data"]["objects"][0]["capitals"][0]["coordinates"]
# capital_name = data_pais["data"]["objects"][0]["capitals"][0]["name"]
alpha_3 = data_pais["data"]["objects"][0]["codes"]["alpha_3"]
# data_pais["data"]["objects"][0]["flag"]
alpha_3

In [ ]:
# TODO parse
# - flag
# - capital
# - area
# - timezones
# - currency
# - languages
# - borders
# - flag png
# - gini index
# - coat of arms

In [ ]:
pd.DataFrame(data_pais["data"]["objects"]).T

In [ ]:
def get_country_data(alpha_3: str):
    file_path = EXTERNAL_DATA_DIR / "restcountriesapi" / f"{alpha_3}.json"
    if not file_path.exists():
        return None

    with open(file_path, "r") as file:
        data = json.load(file)
    return data

In [ ]:
country_data = get_country_data("AGO")

In [ ]:
country_data["data"]["objects"][0]["flag"]["url_png"]
country_data["data"]["objects"][0]["area"]["kilometers"]
country_data["data"]["objects"][0]["borders"]
country_data["data"]["objects"][0]["economy"]["gini_coefficient"]
capitals = ", ".join(
    [x["name"] for x in country_data["data"]["objects"][0]["capitals"]]
)
country_data["data"]["objects"][0]["government_type"]
", ".join([x["name"] for x in country_data["data"]["objects"][0]["languages"]])
len(country_data["data"]["objects"][0]["languages"])

# Worldmeter

In [ ]:
def get_tables_from_website(url) -> list | None:
    response = requests.get(url)
    if response.ok:
        tables = pd.read_html(StringIO(response.text))
        logger.info(f"{len(tables)} tables found in {url}.")
        return tables
    return None


def parse_table(df: pd.DataFrame) -> pd.DataFrame: ...

In [ ]:
url_gdp_by_country = "https://www.worldometers.info/gdp/gdp-by-country/"
gdp_tables = get_tables_from_website(url_gdp_by_country)

In [ ]:
gdp_imf = gdp_tables[0]
gdp_wb = gdp_tables[1]

gdp_imf = gdp_imf[["Country", "GDP (Full Value, US$)", "GDP per Capita (US$)"]]
gdp_imf.columns = ["country", "gdp (us$) imf", "gdp per capita (us$) imf"]

gdp_wb = gdp_wb[["Country", "GDP (Full Value, US$)", "GDP per Capita (US$)"]]
gdp_wb.columns = ["country", "gdp (us$) wb", "gdp per capita (us$) wb"]

In [ ]:
df_gdp = gdp_imf.merge(gdp_wb, on="country")

In [ ]:
url_population = "https://www.worldometers.info/geography/countries-of-the-world/"
population_tables = get_tables_from_website(url=url_population)

In [ ]:
df_population = pd.concat([population_tables[0], population_tables[1]])
df_population = df_population[["Country", "Population 2026"]].reset_index(drop=True)
df_population.columns = ["country", "population 2026"]

In [ ]:
df_demographics = df_population.merge(df_gdp, on="country", how="left")

In [ ]:
# preprocessing data from the SDG report
country_map = {
    "CÃ´te d'Ivoire": "Côte d'Ivoire",
    "DR Congo": "Democratic Republic of the Congo",
    "Laos": "Lao People's Democratic Republic",
    "Saint Kitts & Nevis": "Saint Kitts and Nevis",
    "South Korea": "Republic of Korea",
    "Brunei": "Brunei Darussalam",
    "Czech Republic (Czechia)": "Czechia",
    "United States": "United States of America",
    "Vietnam": "Viet Nam",
    "Sao Tome & Principe": "Sao Tome and Principe",
    "St. Vincent & Grenadines": "Saint Vincent & Grenadines",
    "Russia": "Russian Federation",
}

for i, r in df_demographics.iterrows():
    if r["country"] in country_map:
        df_demographics.at[i, "country"] = country_map[r["country"]]

df[["country", "iso_3"]].merge(df_demographics, on="country", how="left").sort_values(
    by="country"
).to_csv(PROCESSED_DATA_DIR / "worldometer.csv", index=False)

df_aux = (
    df[["country", "iso_3"]]
    .merge(df_demographics, on="country", how="outer")
    .sort_values(by="country")
)

df_aux[(df_aux["iso_3"].isnull()) | (df_aux["population 2026"].isnull())]

# SDG Report

In [ ]:
df_sdg_data = pd.read_excel(
    EXTERNAL_DATA_DIR / "sdg_index" / "database_2026.xlsx", sheet_name="SDR2026 Data"
)

In [ ]:
df_sdg_data = df_sdg_data[
    [
        "Country Code ISO3",
        "country",
        "2026 SDG Index Score",
        "2026 SDG Index Rank",
        "Goal 1 Dash",
        "Goal 1 Trend",
        "Goal 2 Dash",
        "Goal 2 Trend",
        "Goal 3 Dash",
        "Goal 3 Trend",
        "Goal 4 Dash",
        "Goal 4 Trend",
        "Goal 5 Dash",
        "Goal 5 Trend",
        "Goal 6 Dash",
        "Goal 6 Trend",
        "Goal 7 Dash",
        "Goal 7 Trend",
        "Goal 8 Dash",
        "Goal 8 Trend",
        "Goal 9 Dash",
        "Goal 9 Trend",
        "Goal 10 Dash",
        "Goal 10 Trend",
        "Goal 11 Dash",
        "Goal 11 Trend",
        "Goal 12 Dash",
        "Goal 12 Trend",
        "Goal 13 Dash",
        "Goal 13 Trend",
        "Goal 14 Dash",
        "Goal 14 Trend",
        "Goal 15 Dash",
        "Goal 15 Trend",
        "Goal 16 Dash",
        "Goal 16 Trend",
        "Goal 17 Dash",
        "Goal 17 Trend",
        "Poverty headcount ratio at $3.00/day (%)",
    ]
]

In [ ]:
df[["country", "iso_3"]].merge(
    df_sdg_data, how="left", left_on="iso_3", right_on="Country Code ISO3"
).head(10)

In [ ]:
response = requests.get("https://dashboards.sdgindex.org/profiles/")
if response.ok:
    soup = BeautifulSoup(response.text, "html.parser")

In [ ]:
links = soup.find_all("a")
data = []
base_url = "https://dashboards.sdgindex.org/profiles/"
for link in links:
    if (
        link.get("href").startswith("/profiles/")
        and len(link.get("href").replace("/profiles/", "").replace("/", "").strip()) > 0
    ):
        country_name = link.text.strip()
        country_link = link.get("href").replace("/profiles/", "")
        data.append((country_name, base_url + country_link))
df_sdg_profiles = pd.DataFrame(data, columns=["country", "sdg_profile"])

In [ ]:
df_sdg = df_sdg_data.merge(df_sdg_profiles, on="country", how="left")

In [ ]:
# df_sdg.to_csv(PROCESSED_DATA_DIR / "sdg_countries.csv", index=False)

# Other names

In [ ]:
import curl_cffi
import pandas as pd
from bs4 import BeautifulSoup

url = "https://en.wikipedia.org/wiki/List_of_alternative_country_names"
response = curl_cffi.get(url, impersonate="chrome")
soup = BeautifulSoup(response.text, "html.parser")
tables = soup.find_all(class_="wikitable")

  code         name                                  alternative_names
0          Abkhazia  Republic of Abkhazia|Apsny|Aphsny Axwynthkharr...
1  AFG  Afghanistan  Islamic Emirate of Afghanistan|Da Afġānistān I...
2  ALB      Albania  Republic of Albania|Republika e Shqipërisë|Arn...
3  DZA      Algeria  People's Democratic Republic of Algeria|al-Jaz...
4  AND      Andorra  Principality of Andorra|Principat d'Andorra|Pr...

In [ ]:
data = []
for table in tables:
    for row in table.find_all("tr")[1:]:  # ignores the column names row
        cell_data = row.find_all("td")
        if len(cell_data) == 3:  # only process when there are 3 columns
            code, name, names = cell_data
            country_name = name.find("a")["title"].strip()
            other_names = "|".join(
                [x.text.strip() for x in names.find_all("b") if len(x.text.strip()) > 2]
                + [
                    x.text.strip()
                    for x in names.find_all("i")
                    if len(x.text.strip()) > 2
                ]
            )
            data.append((code.text, country_name, other_names))

df_country_names = pd.DataFrame(data, columns=["code", "name", "alternative_names"])
df_country_names.head()

  code         name                                  alternative_names
0          Abkhazia  Republic of Abkhazia|Apsny|Aphsny Axwynthkharr...
1  AFG  Afghanistan  Islamic Emirate of Afghanistan|Da Afġānistān I...
2  ALB      Albania  Republic of Albania|Republika e Shqipërisë|Arn...
3  DZA      Algeria  People's Democratic Republic of Algeria|al-Jaz...
4  AND      Andorra  Principality of Andorra|Principat d'Andorra|Pr...

In [ ]:
df_country_names[df_country_names["name"] == "Papua New Guinea"]
df_country_names[df_country_names["name"] == "Estonia"]["alternative_names"].values[
    0
].split("|")

['Republic of Estonia',
 'Esthonia',
 'Eesti',
 'Eesti Vabariik',
 'Viru',
 'Viro',
 'Estland',
 'Maarjamaa',
 'Igaunija']

In [334]:
for i, r in df_country_names.iterrows():
    for name in [x.lower().strip() for x in r["alternative_names"].split("|")]:
        if name in df[df["iso_3"] == "CHL"]["full_speech"].values[0].lower():
            print(r["name"], name)

Estonia viro
Iceland fold
Lithuania lita
Russia rus
South Africa south
United States america
United States usa
United States usa

In [321]:
df[df["iso_3"] == "CHL"]["full_speech"].values[0].lower().replace(".", "").replace(
    ",", ""
)

"a very very good afternoon to you all secretary general president of the general assembly heads of state and government distinguished delegates particular greetings to the delegation that has traveled with me from chile i wish to greet our minister for foreign affairs our minister for the environment for development and the family our ambassadors our senators and members of parliament and i wish to greet each and every chilean p person greetings and a warm embrace to you all 64 years ago in this same forum the then president of chile horgeandre described our country chile as a large narrow nation between the andes and the pacific extending from there till the moving expanse of the antarctic the land remains where it is what has changed is the world around it what has changed first and foremost is chile for the vast swades of the '9s and until the beginning of the 2000s chile was a success story and a model for many regions and nations our country implemented economic policies that prioritized economic stability openness to trade and private investment in the latin american context in which many nations were facing inflation crisis and external debt chile distinguished itself because it continued to show fiscal responsibility display high rates of growth and poverty reduction what happened then? chile ground to a halt things stagnated it took bad decisions public policies were implemented that increased taxation regulation and obstacles to entrepreneurship we also weathered a very difficult juncture in october 2019 chile then fell to its need knees in our streets for months there was an outbreak of violence chaos reigned and disorder prevailed all of that brought consequences with it investment plummeted employment ground to a standill and homicide levels rose to le rose to an extent that chile had never seen in modern history as a result of the rising tide of organized crime and that all happened until very recently until now distinguished i've come to this forum to tell you that chile is back and that is no slogan it is the very reality of a country that today begins to stride towards development our country our government rather took office with one conviction order does not run counter to freedom order is one of the preconditions of freedom the freedom to walk home worry free and to not be a victim of crime the freedom to run a business and not be stymied by the action of the state the freedom to invest and not find yourselves in a situation where the rules of the game are continually changing we have been in government for six years and we're getting our house in order today chile is a safer more competitive country and a nation with far less red tape chile is a safer country in chile in the first 6 months of this year the rate of homicides decreased to the tune of 115% and we are now approaching preandemic homicide levels our borders are under better control we have our border shield plan and that has made it possible to induce irregular entry by 86% and we have deported 50% more people than we did last year people do not come in through the window they come in through their ports with all their documents in order in the same vein we have the santiago accord and here i thank our minister for foreign affairs who was the person who spearheaded that initiative and this is a security initiative many south american nations have acceded to it so that we can coordinate to effectively combat transnational organized crime our work is not yet done it has only just started a safer country is a country with more trust and where there is trust there is more growth employment and investment we are also today a more competitive nation only a few weeks ago chile adopted the most significant economic reform of recent decades we approved a reduction to business tax it's now gone from 27 to 23% this tax had only been on the increase since 1990 it had never decreased we have also temporarily reduced housing purchase tax and we have launched an initiative for capital repatriation there's better tax stability too we now have less red tape we are also dismantling what we call this ideology of always having to issue permits this is if you like a sort of hidden bureaucracy which stops business projects from forging ahead in six months in the last six months we've had requests to invest more than $44 billion in our economy and these are these investment project applications are being assessed by our environmental evaluation systems more than $33000 billion dollars rather have been approved for projects that had been in the wings for years we have unleashed $17 billion dollars for environmental projects we are taking tangible actions that are changing the very course of chile and bringing us closer to envelopment development the economy is not yet taking off and unemployment is still plunging thousands of families into uh anguish but unemployment is hard and high but it will change change will come results are slow to materialize but structural reforms are underway we know where we're going and we're not simply reacting without having any clear course in mind after storms the sun always comes out after winter spring always arrives and after years of deadlock chile is back there are many reasons that can explain how we got to where we are but there's only one path that we need to follow for chile to once again take off spread its wings and fly that is the path of unity unity between all of those that defend freedom and want to see chile's people thrive there are many things that might separate the right and the left in chile but we are united by our desire to see chile grow once more and become a safer nation delegates people from the investment world are listening to is to us and i say to you choose chile to invest you will find clear rules that do not change dayto-day you will find courts that function contracts that are abided by and a state ready to facilitate investment chile understands that in a multi-olar world institutional stability is not a luxury it is a need for example we are a pioneer in the energy transition chile possesses around a quarter of global lithium reserves and we are the largest productor of copper on the planet chile has a lot of sunlight the heat of the sun a long pacific coast lakes rivers volcanoes that can create vast stores of energy chile also has the straight of magayan a crucial alternative route for global trade our nation will become the bridge and the port for the bioanic corridors that will unite america with asia this richness this wealth is not only fortune that we have in our coffers it brings with it responsible responsibility to you chile will never renounce its sovereignty neither will it cease to exploit its own minerals at the same time we have we have our sovereignty of course but at the same time we say that the energy of the future must serve humankind and energy must not be held hostage by monopolies or actors that do not abide by the rules please make no mistake here it is possible to reconcile growth and sustainability the two are inseparable chile understands that environmental pro environmental protection rather and economic progress form part of one single development strategy one in which investment and innovation are lynchpins when it comes to improving the quality of life of our people sustainable development requires robust institutions clear rules timely decisions and effective administration a able to turn commitments and diagnoses into tangible results for both people and the environment president i now wish to turn to a discussion of our continent latin america because i sincerely believe that the coming decade can be ours for the first time in a long time latin american governments are really truly uniting and working together not by simply issuing communicates but getting to know each other and speaking to each other to really come up with common plans against transnational organized crime migration control and coming together to forge joint development opportunities latin america is the continent of the future and those of us that lead the continent today are ready to give momentum to that change relations with our neighbors peru bolivia and argentina are in fine fettle we are resuming relations with venezuela under a new leadership we've opened doors that were closed for years some people will say to us that we don't or they don't understand this change but others or that they don't understand this this move on our part others will say that we're simply un new unthinking allies of this country but we're neither one or the other we recognize the reality for what it is we value change where it exists and we offer support we're of the view that venezuela has before it a historic opportunity to reconcile with its best democratic traditions with its institutions and with the millions of its children that are now scattered across our continent that want to return this path will be a demanding one chile is ready and willing to provide the help necessary after two decades of tensions latin america wants this history to have a happy conclusion delegates this assembly cannot remain indifferent to the wars and conflicts that are raging around the world these open conflicts do not only threaten the stability of many regions rather they damage the entire world chile like many countries represented in this chamber imports almost all of the oil it consumes and has been directly affected by manifold wars i'm not talking here about abstract geopolitics the impact is expressed in the cost of bread transport and harvest inflation that refuses to hold still tax that taxes that do not decrease investment delayed and jobs that don't arrive entire countries that were really taking off and triumphing have once again ground to a halt and seen stagnation settle in for wars that they didn't start and that they can't stop for therefore our appeal to you is direct wars must stop wars do not only drain the blood of those that fight them they plunge people into poverty indeed they do that for the whole world we all lose with wars and we've lost too much the united nations has a role to play and it must do so with the character and the dynamism that it has it has not yet shown delegates here is the most uncomfortable thing i came to say uh the hardest pill to swallow in my speech this organization has not been commensurate with the challenges of our times it's not only a leadership problem one of the present or the future but rather a problem in terms of action for decades and for several reasons the united nations has not been part of the solution to the problems i've outlined it's we cannot simply continue to play by the same rules of an order that was established in 1945 in 2026 what we've seen is the development of a un architecture that holds too many discussions and is too quick to act a security council that reflects the political arena of 1945 and the reality and not the reality of 2026 we have red tape that continues to proliferate as is true for indeed many countries we're seeing agendas that however noble they might appear have ultimately postponed what this organization committed to do with the with its founding charter that is maintain peace protect right life and defend the freedom of its peoples we believe in the united nations and believing in the united nations means ensuring that the organization discharges its mandate i propose three things reducing bureaucracy and focusing our resources where there are lives at stake we must suspend agendas that are not priorities to return the spotlight to those that really are priorities we must reform the security council not as a symbolic gesture but as a vital prerequisite to ensure that the council's decisions are once again respected and upheld chile signed the san francisco charter and has been present ready and willing to defend all its causes all of its causes rather we have we are committed to the high seas agreement known as the bbj and we proposed valpariso as the headquarters of its executive secretariat that means that we now have the first un body to ever have had a headquarters in latin america and this is an agreement which brings together many different sectors in chile to play this role this housing of this headquarters is an expression of the multilateralism that we believe in a tangible ambitious and able to prove to yield results there needs to be a multilateralism that is effective and efficient and allow me to say that the reforms i talked about cannot wait while we discuss how to modernize institutions created in 1945 we're seeing the emergence of the most powerful technology that humankind has ever known and no one's governing it artificial intelligence is not only a technical matter that we can delegate to experts it is an ethical challenges and and it's a geopolitical issue we reject the false dilemma between innovation and responsibility we don't believe that going quicker is always better and neither are we going to turn our back on opportunities as a result of fear for our country ai can amount to and mean growth of between 10% and 20% as such we are choosing the path that we call responsible one of responsible pace that means making progress as quickly as our ability to administer progress allows we have we have regulations that make things possible that do not hamper progress we have investment in talent and in energy and we have rigorous assessments of everything that's happening we want to lead from a position of knowledge and not fear and i say this in this room for one reason the united nations must be able to bring humankind together to discuss a technology that will decide the fate of this century nothing can simply be resolved by an algorithm mr president allow me to go back to the beginning the president that i talked about that spoke here 74 years ago spoke on behalf of his people and discarded ideological differences he said that chile will continue working fervently and with deep belief in the principles of the un charter and the fact that they must be tangibly expressed we believe in the in human rights and at that time in 1945 we had seven 7 million inhabitants today we have 20 million the world has changed and we have too but what he said remains relevant and once again i say before you that chile has come back to establish order with order come freedom returns trust returns and it has done we are investment has returned and investment brings work chile as getting back on its feet as quickly as it fell and it's come to say to the world that a country can recover and a country recovers with votes agreements laws and results but i have one more thing to say that is that a future can be built without being held hostage by others decisions latin america can be the continent of the coming decade not because someone gives it permission to be just that but because we have the desire and the ability to be that country and that continent we want to lead the path to that goal chile is back thank you"